// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSt4OyeV0IzPI35ulQ5cQhn1SU_T4DOA0',
    appId: '1:561253836819:web:e010d24be502513ceb37e6',
    messagingSenderId: '561253836819',
    projectId: 'infant-hearing-app',
    authDomain: 'infant-hearing-app.firebaseapp.com',
    storageBucket: 'infant-hearing-app.firebasestorage.app',
    measurementId: 'G-MT9YDJTFS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh1FNr1KRVjBZE5yOPMLt6-Z15H8SrZtM',
    appId: '1:561253836819:android:dafbce380d76546deb37e6',
    messagingSenderId: '561253836819',
    projectId: 'infant-hearing-app',
    storageBucket: 'infant-hearing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4sIkgc7Oym0AQ1GSP83nmjodt2XIvChk',
    appId: '1:561253836819:ios:bfc7187a58760036eb37e6',
    messagingSenderId: '561253836819',
    projectId: 'infant-hearing-app',
    storageBucket: 'infant-hearing-app.firebasestorage.app',
    iosBundleId: 'com.example.infantHearingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4sIkgc7Oym0AQ1GSP83nmjodt2XIvChk',
    appId: '1:561253836819:ios:bfc7187a58760036eb37e6',
    messagingSenderId: '561253836819',
    projectId: 'infant-hearing-app',
    storageBucket: 'infant-hearing-app.firebasestorage.app',
    iosBundleId: 'com.example.infantHearingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSt4OyeV0IzPI35ulQ5cQhn1SU_T4DOA0',
    appId: '1:561253836819:web:d41c5e772ebce6feeb37e6',
    messagingSenderId: '561253836819',
    projectId: 'infant-hearing-app',
    authDomain: 'infant-hearing-app.firebaseapp.com',
    storageBucket: 'infant-hearing-app.firebasestorage.app',
    measurementId: 'G-8GEH8N8WFT',
  );
}
